name: "Build"

on:
  - push
  - pull_request

jobs:
  build: # Check build on various OSes

    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          # - windows-latest Windows doesn't work yet
        ocaml-version:
          # Don't include every versions. OCaml-CI already covers that
          - 4.11.1
        include:
          - os: ubuntu-latest # Enable coverage only on a single build
            send-coverage: true
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      # Clone the project
      - uses: actions/checkout@v2

      # Setup
      - name: Setup OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}
          opam-local-packages: |
            odoc-parser.opam

      - name: Install dependencies
        run: opam install -y --deps-only -t ./odoc-parser.opam

      - name: dune runtest
        run: opam exec -- dune runtest

